### PR TITLE
Catch StringIndexOutOfBoundsException first

### PR DESCRIPTION
**Pull request by sergiishamrai-okta**
Fix for https://github.com/okta/okta-commons-java/issues/70

### CODE REVIEW

**Review by BalusC — APPROVED** [review]

**Review by arvindkrishnakumar-okta — CHANGES_REQUESTED** [review]
I think we should be fixing the root cause of this exception (see how the `version` string looks and fix the string parsing login) instead of swallowing it and returning `UNKNOWN_VERSION`.

**Comment by ricgil** [comment]
Hi there, any chance fixing this? We are having this issue in a WAS v8.5 running in a container and our systems team says there's a difference in the output so the logic would be "correct" for a WAS directly on bare metal but not in our case. Anyway, understanding your view @arvindkrishnakumar-okta , this is causing a runtime exception and blocking completely the use of the verifier lib and this is only used to set up an user agent on the HTTP calls. It might be interesting to really use the UNKNOWN_VERSION fallback when you can't guess the version from a string. That kind of output from a server doesn't seems like the most reliable source of truth. It's not working on one of our projects but it can also break easily on a software update imho. What do you think? It would be possible to use that fallback in this case as @sergiishamrai-okta  proposed?

**Review by arvindkrishnakumar-okta — APPROVED** [review]

**Comment by ricgil** [comment]
Awesome, many thanks :). Sorry, my fault for sure, I can't find how's the release cycle. We are having the issue from the verifier lib. It would be great to know when will be released a new library version and integrated from the verifier lib.

**Comment by ricgil** [comment]
Oh, also let you know @arvindkrishnakumar-okta and @sergiishamrai-okta ... it wasn't working for us because that message from Websphere is internationalized and our server shows an output in spanish. So no "Installed product" string, it was "Producto instalado". Apart from thinking on a regex that could ignore i18n issues, it seems this info is only available this way or using the [Server MBean](https://www.ibm.com/docs/en/was/8.5.5?topic=SSEQTP_8.5.5/com.ibm.websphere.javadoc.doc/web/mbeanDocs/Server.htm), but I guess that's overkill for the purpose.

**Pull request merged**
