### PR TITLE
Add Android version into user agent string.

### PR DESCRIPTION
**Pull request by JayNewstrom**
This will add a segment to the user agent that looks like `android/29`.

### CODE REVIEW

**Review by arvindkrishnakumar-okta — APPROVED** [review]

**Review by bdemers — APPROVED** [review]
Looks good to me, 
I'm guessing the system properties don't return the Android info?
```java
System.getProperty("os.name")
System.getProperty("os.version")
```

What does `System.getProperty("java.version")` return?

Do we need any null checks for this around line 109-111?

**Comment by arvindkrishnakumar-okta** [comment]
Would be nice if you can add a test (https://github.com/okta/okta-commons-java/blob/master/lang/src/test/groovy/com/okta/commons/lang/ApplicationInfoTest.groovy).

**Comment by JayNewstrom** [comment]
@bdemers os name/version look like `Linux/4.14.112+`. `java.version` returns 0. So the string might look something like `java/0 Linux/4.14.112+ android/29` in total.

@arvindkrishnakumar-okta The code to detect android is using classes that don't exist where the tests run, so it would never execute that code path. If you have an idea on how to test it, I'd be more than happy to implement it. That being said, none of the other server side runtimes (swing, tomcat, etc) have tests either, which is how I justified not having a test for this in the first place.

**Comment by arvindkrishnakumar-okta** [comment]
> @bdemers os name/version look like `Linux/4.14.112+`. `java.version` returns 0. So the string might look something like `java/0 Linux/4.14.112+ android/29` in total.
> 
> @arvindkrishnakumar-okta The code to detect android is using classes that don't exist where the tests run, so it would never execute that code path. If you have an idea on how to test it, I'd be more than happy to implement it. That being said, none of the other server side runtimes (swing, tomcat, etc) have tests either, which is how I justified not having a test for this in the first place.

nvm, 🚢

**Comment by bdemers** [comment]
Java/0 is a bit odd, but it’s also probably actuate considering it’s Android. 🙃

Thanks for the follow up!

**Pull request merged**
